In [15]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import csv

In [3]:
def tenmat(data,index):
    x,y,z = data.shape
    iList = [x,y,z]
    total = list()
    temp = 0
    
    if index == 0:
        temp = 0
    elif index == 1:
        temp = 2 
    elif index == 2:
        temp = 1
    else:
        raise Exception("index error")
        
    index = temp
    for i in range(iList[index]):
        if index==0:
            total.append(data[i,:,:].T)
        elif index==1:
            total.append(data[:,i,:])
        elif index==2:
            total.append(data[:,:,i].T)
        else:
            raise Exception("error")
    R = np.column_stack(tuple(total))
    return R

In [4]:
data = np.zeros((3,2,4))
data[0,0,0]=1
data[0,1,0]=1
data[1,0,1]=1
data[2,1,2]=1

In [5]:
print(data)
A1 = tenmat(data,0)
A2 = tenmat(data,1)
A3 = tenmat(data,2)
print(A1)
print(A2)
print(A3)
[u1,v1,w1] = np.linalg.svd(A1)
[u2,v2,w2] = np.linalg.svd(A2)
[u3,v3,w3] = np.linalg.svd(A3)
print(u1.shape)
print(u2.shape)
print(u3.shape)

[[[ 1.  0.  0.  0.]
  [ 1.  0.  0.  0.]]

 [[ 0.  1.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  1.  0.]]]
[[ 1.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.]]
[[ 1.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]]
[[ 1.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.]]
(4, 4)
(2, 2)
(3, 3)


In [6]:
[u1,v1,w1] = np.linalg.svd(A1)
[u2,v2,w2] = np.linalg.svd(A2)
[u3,v3,w3] = np.linalg.svd(A3)

In [7]:
def ttm(tensor,index,matrix):
    
    x,y,z = tensor.shape
    iList = [x,y,z]
    
    mx,my = matrix.shape
    assert iList[index]==my,"dimension not equal "
    if index==0:
        result = np.zeros((mx,y,z))
    elif index==1:
        result = np.zeros((x,mx,z))
    elif index==2:
        result = np.zeros((x,y,mx))
        
    print(x,y,z)
    print(mx,my)
        
    xx,yy,zz = result.shape
    
    total = 0
    for i in range(xx):
        for j in range(yy):
            for k in range(zz):
                total = 0
                if index==0:
                    for l in range(x):
                        total += tensor[l,j,k]*matrix[i,l]
                elif index==1:
                    for l in range(y):
                        total += tensor[i,l,k]*matrix[j,l]
                elif index==2:
                    for l in range(z):
                        total += tensor[i,j,l]*matrix[k,l]
                result[i,j,k] = total
    return result


In [8]:
print(A1)
print(A2)
print(A3)
print(u1.shape)
print(u2.shape)
print(u3.shape)


[[ 1.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.]]
[[ 1.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]]
[[ 1.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.]]
(4, 4)
(2, 2)
(3, 3)


In [9]:
U1 = u1.copy()
U2 = u2.copy()
U3 = u3.copy()
print(U1.shape)
print(U2.shape)
print(U3.shape)
# U1 = np.delete(U1,-1,1)
# U2 = np.delete(U2,-1,1)
# U3 = np.delete(U3,-1,1)
print(U1.shape)
print(U2.shape)
print(U3.shape)

(4, 4)
(2, 2)
(3, 3)
(4, 4)
(2, 2)
(3, 3)


In [10]:
print(data.shape)

temp = ttm(data,2,U1.T)
print(temp.shape)
temp = ttm(temp,1,U2.T)
print(temp.shape)
S = ttm(temp,0,U3.T)
print(temp.shape)
print(S)

(3, 2, 4)
3 2 4
4 4
(3, 2, 4)
3 2 4
2 2
(3, 2, 4)
3 2 4
3 3
(3, 2, 4)
[[[ -1.41421356e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
  [  3.33066907e-16   0.00000000e+00   0.00000000e+00   0.00000000e+00]]

 [[  0.00000000e+00   0.00000000e+00  -7.07106781e-01   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00   7.07106781e-01   0.00000000e+00]]

 [[  0.00000000e+00  -7.07106781e-01   0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00  -7.07106781e-01   0.00000000e+00   0.00000000e+00]]]


In [11]:
A = ttm(S,2,U1)
A = ttm(A,1,U2)
A = ttm(A,0,U3)
print(A)
print(data)

3 2 4
4 4
3 2 4
2 2
3 2 4
3 3
[[[  1.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
  [  1.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]]

 [[  0.00000000e+00   1.00000000e+00   0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   1.11022302e-16   0.00000000e+00   0.00000000e+00]]

 [[  0.00000000e+00   0.00000000e+00   1.11022302e-16   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00   1.00000000e+00   0.00000000e+00]]]
[[[ 1.  0.  0.  0.]
  [ 1.  0.  0.  0.]]

 [[ 0.  1.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  1.  0.]]]


In [12]:
print(data)

[[[ 1.  0.  0.  0.]
  [ 1.  0.  0.  0.]]

 [[ 0.  1.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  1.  0.]]]


In [14]:
with open(r'./data/item.txt','r') as f:
    items = list()
    for line in f:
        line = line.rstrip('\n')
        if line not in items:
            items.append(line)
print(len(items))

2632


In [29]:
userMap = dict()
itemMap = dict()
classSet = set()


userCount = 0
itemCount = 0

userClass = list(range(120))
with open(r'./data/original_data.csv','r') as f:
    reader = csv.reader(f)
    mark = True
    result = list()
    
    
    for line in reader:
        if mark:
            mark = False
            header = line
        
        user = line[0] 
        user_class  = line[1] 
        item_id = line[2]
        value = line[4]
        
        result.append([user,item_id,user_class,value])
        
        if user not in userMap:
            userMap[user] = userCount
            userCount += 1    
        
        if item_id not in itemMap:
            itemMap[item_id] = itemCount
            itemCount += 1
        
        classSet.add(user_class)
        
            

In [30]:
classSort = sorted(classSet,reverse=False)
classMap = [(i,s) for i,s in zip(classSort,range(len(classSort)))]
classMap = dict(classMap)


In [31]:
x,y,z = len(userMap.keys()),len(itemMap.keys()),len(userClass)
X_data = np.zeros((x,y,z))
for u,i,c,v in result:
    
    uIndex = userMap[u]
    iIndex = itemMap[i]
    cIndex = classMap[c]
    
    X_data[uIndex,iIndex,cIndex] = int(v) 
    

MemoryError: 

[1, 2, 3, 4, 6]
